name: inspector_brandon_frontend
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.1
  font_awesome_flutter: 9.2.0
  animated_text_kit: 4.2.1
  google_fonts: 2.1.0
  flutter_screenutil: 5.0.1
  camera: ^0.9.4+20
  camera_web: ^0.2.1+3
  video_player: ^2.4.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.0
  lints: 1.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
